### ISSUE TITLE
parse emoji error

### ISSUE THREAD

**Issue by iamcco** [vim-jp/vim-vimlparser#129]
t.vim

``` vim
let test = "🐥"
```

`node vimparser.js --neovim t.vim`

**Comment by tyru** [comment]
What is the error message?

**Comment by iamcco** [comment]
error output

```
/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:159
      return encodeURIComponent(obj).replace(/%../g, ' ').length;
             ^

URIError: URI malformed
    at encodeURIComponent (<anonymous>)
    at viml_len (/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:159:14)
    at StringReader.__init__ (/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:3765:20)
    at new StringReader (/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:3752:41)
    at main (/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:21:13)
    at Object.<anonymous> (/Users/aioiyuuko/my/vim-language-server/lib/vimparser.js:5640:3)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
```

**Comment by blueyed** [comment]
Just for reference: vint parses this fine already:
```vim
scriptencoding utf8

let test = '🐥'
```

**Comment by mattn** [comment]
Yes, it is caused by using surrogate pair with encodeURIComponent.
